### ISSUE TITLE
Lernrate -> Learn Rate

### ISSUE THREAD

**Issue by MRIO** [ianchanning/neural-network-js#1]
Thanks for your nice widget! However, there's something of an ugly typo. What's now 'lernrate' should be 'learn rate', or better 'learning rate'.

**Comment by ianchanning** [comment]
Hi there,

This seems like an AI bot request. Could you confirm whether or not this is a bot account?

Cheers,

Ian

**Comment by MRIO** [comment]
Nope, not a bot account =]
It would have been impressive if it could have spotted a misspelled title in a widget. Nope, that’s still a human thing ;D

**Comment by ianchanning** [comment]
I believe this is a bot - there is no 'lern' in my code. This is not a widget.

**Comment by ianchanning** [comment]
Presume bot

**Comment by MRIO** [comment]
My mistake in reporting (it wasn’t your codebase, but the one i attached).

If you want to double check my existence, you can google me. I’m a computational neuroscientist working in Rotterdam/Netherlands.

https://github.com/Dennis198/Perceptron-Visualizer￼
Dennis198/Perceptron-Visualizer: A web-based animation tool to visualize perceptron algorithm
github.com
